# .github/workflows/build-image.yml
name: Build and Tag Docker Image

on:
  release:
    types: [published]

env:
  SERVICE_NAME: nextjs-gutenberg-llm
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ env.SERVICE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }} # Checkout the tagged release

      - name: Configure Docker authentication (GHCR)
        run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }}

      - name: Build and tag Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.ref_name }} .

      - name: Push Docker image to GitHub Container Registry (GHCR)
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.ref_name }}

        